name: Auto Request Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Get changed files
      #   id: file_changes
      #   run: |
      #     echo "Getting changed files..."
      #     echo "Base: ${{ github.event.pull_request.base }}"
      #     echo "Head: ${{ github.event.pull_request.head }}"
      #     echo ::set-output name=files::$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})

      - name: Extract usernames
        id: extract_usernames
        run: |
          echo "Extracting usernames..."
          usernames=($(git log --pretty=format:"%cn" ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | sort -u))
          echo "Usernames: $usernames"
          echo "::set-output name=usernames::$usernames"

      - name: Request reviews
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Requesting reviews..."
          reviewers="${{ steps.extract_usernames.outputs.usernames }}"
          echo "Reviewers: $reviewers"
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
            -d '{"reviewers": ["mbilawisdom"]}'
