name: Auto Request Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get pull request creator username
        id: get_pull_request_creator_username
        run: |
          creator=$(jq -r '.pull_request.user.login' ${{ github.event_path }})
          echo "::set-output name=creator::$creator"
          
      - name: Extract reviewers emails from commits
        id: extract_reviewers_emails
        run: |
          emails=($(git log --pretty=format:"%ae" e246ac967be580511c87bf3f22d8a36fbd8905b2..5ecca7b1a6383e8d290b1f71aa39a5ab5922e3af | sort -u))

          # Join the emails array back into a comma-separated string
          emails=$(IFS=','; echo "${emails[*]}")

          echo "emails after : $emails"
          echo "::set-output name=emails::$emails"

      - name: Get reviewers GitHub usernames
        id: get_reviewers_usernames
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          emails="${{ steps.extract_reviewers_emails.outputs.emails }}"

          # Create an empty array to store reviewers GitHub usernames
          reviewers_usernames=()

          # Loop through the reviewers emails and get their GitHub usernames
          IFS=',' read -ra emails_array <<< "$emails"
          for email in "${emails_array}"; do
            echo "email : $email"
            echo "url "https://api.github.com/search/users?q=$email+in:email""
            # Get the GitHub username from the email
            username=$(curl -s -X GET \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/search/users?q=$email+in:email" \
            | jq -r '.items[0].login')
            echo "gusername : $username"
          done



      - name: Extract possible reviewers from commits
        id: extract_reviewers
        run: |
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
          usernames=($(git log --pretty=format:"%cn" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | sort -u))
          usernames=$(echo "${usernames[@]}" | tr ' ' '\n' | sort -u | tr '\n' ',')

          # Remove any leading or trailing commas
          usernames="${usernames#,}"
          usernames="${usernames%,}"

          echo "Usernames : $usernames"
          echo "::set-output name=usernames::$usernames"

      - name: Get valid extracted reviewers
        id: get_valid_extracted_reviewers
        run: |
          extracted_reviewers="${{ steps.extract_reviewers.outputs.usernames }}"
          creator="${{ steps.get_pull_request_creator_username.outputs.creator }}"

          # the creator of the pull request is not a valid reviewer
          invalid_reviewers=("GitHub" "dependabot[bot]" "$creator" "dependabot-preview[bot]")

          # Create an empty array to store valid reviewers
          valid_reviewers=()

          # Loop through the extracted reviewers and check if they are valid
          IFS=',' read -ra reviewers_array <<< "$extracted_reviewers"
          for reviewer in "${reviewers_array[@]}"; do
            # Check if the reviewer is not in the invalid reviewers array
            if [[ ! " ${invalid_reviewers[@]} " =~ " $reviewer " ]]; then
              valid_reviewers+=("$reviewer")
            fi
          done

          # Join the valid reviewers array back into a comma-separated string
          valid_reviewers_string=$(IFS=','; echo "${valid_reviewers[*]}")

          echo "Valid reviewers: $valid_reviewers_string"

          # Set the output to be used in the next step
          echo "::set-output name=valid_reviewers::$valid_reviewers_string"

      - name: Get default reviewers
        id: get_default_reviewers
        env:
          DEFAULT_REVIEWERS: ${{ vars.DEFAULT_REVIEWERS }}
        run: echo "::set-output name=default_reviewers::$DEFAULT_REVIEWERS"

      - name: Get valid default reviewers
        id: get_valid_default_reviewers
        run: |
          default_reviewers="${{ steps.get_default_reviewers.outputs.default_reviewers }}"
          creator="${{ steps.get_pull_request_creator_username.outputs.creator }}"

          # the creator of the pull request is not a valid reviewer
          invalid_reviewers=("GitHub" "dependabot[bot]" "$creator" "dependabot-preview[bot]")

          # Create an empty array to store valid default reviewers
          valid_default_reviewers=()

          # Loop through the default reviewers and check if they are valid
          IFS=',' read -ra default_reviewers_array <<< "$default_reviewers"
          for default_reviewer in "${default_reviewers_array[@]}"; do
            # Check if the default reviewer is in the valid reviewers array
            if [[ ! " ${invalid_reviewers[@]} " =~ " $default_reviewer " ]]; then
              valid_default_reviewers+=("$default_reviewer")
            fi
          done

          # Join the valid default reviewers array back into a comma-separated string
          valid_default_reviewers_string=$(IFS=','; echo "${valid_default_reviewers[*]}")

          echo "Valid default reviewers: $valid_default_reviewers_string"

          # Set the output to be used in the next step
          echo "::set-output name=valid_default_reviewers::$valid_default_reviewers_string"

      - name: Request reviews
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          extracted_reviewers="${{ steps.get_valid_extracted_reviewers.outputs.valid_reviewers }}"
          default_reviewers="${{ steps.get_valid_default_reviewers.outputs.valid_default_reviewers }}"  

          # If there are no extracted reviewers, use the default reviewers
          if [[ $extracted_reviewers == '' ]]; then
            reviewers=$default_reviewers
          else
            reviewers=$extracted_reviewers
          fi

          # Assign the PR to two random reviewers
          IFS=',' read -ra reviewers_array <<< "$reviewers"
          # Shuffle the reviewers array
          shuffled_reviewers=($(shuf -e "${reviewers_array[@]}"))

          # Get the first two reviewers from the shuffled array
          random_reviewers=("${shuffled_reviewers[@]:0:2}")

          random_reviewers_string=$(IFS=','; echo "${random_reviewers[*]}")

          # Get the first reviewer
          first_reviewer="${random_reviewers[0]}"
          # Get the second reviewer
          if [[ ${#random_reviewers[@]} -eq 1 ]]; then
            second_reviewer=""
          else
            second_reviewer="${random_reviewers[1]}"
          fi

          echo "Reviewers: $random_reviewers_string"
          echo "First reviewer: $first_reviewer"
          echo "Second reviewer: $second_reviewer"

          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
            -d '{"reviewers":["'"$first_reviewer"'", "'"$second_reviewer"'"]}'
